print("Enter your name : ")
name = input()
print("My name is " + name)
print("Enter your Class ")
Class= input()
print("I read in class :" + Class)
print("Enter your GPA in Class 8:")
number=input()
print("My GPA in class 8 was : " + number)
